\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{sduthesis}[Thesis template for undergraduates of SDU]


% 基于ctexbook的类
\LoadClass[openany]{ctexbook}

% 导入各项配置
\input{config/config-main.tex}
\input{config/config-coverpage.tex}
\input{config/config-abstract.tex}
\input{config/config-contents.tex}
\input{config/config-bibliography.tex}
\input{config/config-acknowledgement.tex}
\input{config/config-appendix.tex}


\endinput
